---
title: "Traffic analysis for the past `r as.numeric(params$daysback)` Days"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: styles.css
params:
  content_guid: "d2a35487-2270-438a-818d-dbb4dd195b6b"
  daysback: '365'
resource_files:
- config.yml
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(DT)
library(plotly)
library(ggplot2)
library(shiny)
library(lubridate)
library(blastula)
library(prettyunits)
library(connectapi)
library(config)

source("themes.R")

# Activate correct configuration
# "production" for RSConnect deployment or,
# "default" for local development work
si <- Sys.info()
if (si[["user"]] == "rstudio-connect") {
  Sys.setenv(R_CONFIG_ACTIVE = "production")
} else {
  Sys.setenv(R_CONFIG_ACTIVE = "default")
}

connect_server  <- Sys.getenv(config::get("server"))
connect_api_key <- Sys.getenv(config::get("key"))

```

```{r fetch-data, include=FALSE}
days_back <- as.numeric(params$daysback)

default_content_title <- "Unknown (Deleted Content?)"

report_from <- lubridate::today() - lubridate::ddays(days_back)

# Modified for local use
client <- connect(
  server = connect_server,
  api_key = connect_api_key
  )
shiny <- get_usage_shiny(
  client,
  content_guid = params$content_guid,
  from = report_from,
  limit = Inf
) %>%
  mutate(
    started = lubridate::ymd_hms(started),
    ended = lubridate::ymd_hms(ended),
    session_duration = ended - started
    ) %>%
  filter(session_duration > lubridate::dseconds(5))
content <- get_usage_static(
  client,
  from = report_from,
  limit = Inf
)

content_info <- get_content(client, guid = params$content_guid)

all_users <- get_users(client, page_size = 500)

data_arr <-   list(shiny = shiny, content = content)
```


This report provides traffic information for the following Shiny application: `r content_info$title`.  


In order to view traffic information about a different application, please enter its ID in the left pane of this report. 

Row 
-----------------------------------------------------------------------

### Number of visits

```{r}
visits <- nrow(data_arr$shiny)
valueBox(visits, icon = "fa-users")
```

### Shiny Sessions Over Time

```{r shiny_over_time}
data_arr$shiny %>%
  mutate(
    month = round_date(started, "month")) %>% 
  filter(month > today() - ddays(days_back),
         month <= floor_date(today(), "month")#,
         #year(month) == year(today())
  ) %>% 
  group_by(month) %>% 
  summarise(visits = n()) %>% 
  arrange(desc(visits)) %>% 
  {ggplot(., aes(as.Date(month), visits)) + 
      geom_line() +
      scale_x_date(date_labels = "%b-%Y") +
      theme_rstudio() + 
      labs(
        title = paste0(content_info$title, ": Monthly traffic analysis"),
        y = "# of visits by month",
        x = NULL
      )} %>%
  ggplotly(tooltip = c("y")) %>%
  config(displayModeBar = F)
#ggsave(filename = "aimm-traffic.png", width = 14, height = 12, units = "cm")
```
